version: '3.8'

services:
  frontend:
    image: mbakgun/dockerflex-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    image: mbakgun/dockerflex-backend:latest
    ports:
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge