services:
  frontend:
    image: mbakgun/dockerflex-frontend:latest
    hostname: dockerflex-frontend
    container_name: dockerflex-frontend
    ports:
      - "3200:3200"
    environment:
      - VITE_API_URL=/api
      - VITE_BACKEND_URL=http://backend:4200
    networks:
      - app-network

  backend:
    image: mbakgun/dockerflex-backend:latest
    hostname: dockerflex-backend
    container_name: dockerflex-backend
    expose:
      - "4200"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    privileged: true
    user: root
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

networks:
  app-network:
    driver: bridge