services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    hostname: dockerflex-frontend
    container_name: dockerflex-frontend
    restart: unless-stopped
    ports:
      - "3200:3200"
    environment:
      - VITE_API_URL=/api
      - VITE_BACKEND_URL=http://backend:4200
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    hostname: dockerflex-backend
    container_name: dockerflex-backend
    restart: unless-stopped
    expose:
      - "4200"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network
    privileged: true
    user: root
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH

networks:
  app-network:
    driver: bridge