services:
  frontend:
    image: mbakgun/dockerflex-frontend:latest
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
      - frontend_node_modules:/app/node_modules
      - frontend_vite:/app/.vite
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  backend:
    image: mbakgun/dockerflex-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app:cached
      - backend_node_modules:/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
  frontend_vite:
  backend_node_modules: